### ISSUE TITLE
Global Env File

### ISSUE THREAD

**Issue by ethikz** [kohkimakimoto/atom-atomenv#5]
I've tried creating an .`atomenv.cson` file in my `.atom` directory and did the auto-load but when I try to use the variables in the `.atomenv.cson` file they don't render except as plain text and the file is in the same directory as the atom `config.cson`

`.atomenv.cson`

```
env:
  beautifyAnalyticsUserId: "..."
  exceptionReportingUserId: "..."
```

`config.cson`

```
"*":
  "atom-beautify":
    general:
      _analyticsUserId: "${atom.config.get('atomenv.env.beautifyAnalyticsUserId')}"
```

This part though when loading it shows it loaded Atomenv in the console but when I run `atom.config.get()` I do not see `atomenv` in the array

I've even tried

```
"*":
  "atom-beautify":
    general:
      _analyticsUserId: "${env.beautifyAnalyticsUserId}"
```

Is it not meant to run as global environment or am I missing something?
